name: 'product_warehouse_dbt'
version: '1.0.0'

profile: 'product_warehouse_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  product_warehouse_dbt:
    staging:
      +materialized: view
      +schema: staging_layer
    marts:
      +materialized: table
      +schema: analytics
